#!/bin/env bash

SRC=build-ambit-x86-64
TARGET=$SRC/target-system
FNAME=ambit.hm-500g1-300.tar
#DST=a@81.1.215.214:/tmp
DST=root@192.168.2.35:/tmp
cmake --build $SRC -j8

mkdir -p $TARGET
mkdir -p $TARGET/usr/local/bin
mkdir -p $TARGET/usr/local/lib
mkdir -p $TARGET/usr/local/share
mkdir -p $TARGET/usr/local/share/gui

cp $SRC/src/gui/gui $TARGET/usr/local/bin
cp $SRC/src/libs/libaem/libaem.so $TARGET/usr/local/lib
cp $SRC/src/libs/libwe/libwe.so $TARGET/usr/local/lib
cp $SRC/src/libs/ambit-gui-core/libgui-core.so $TARGET/usr/local/lib
cp system/etc/cnc-ctrl/Roboto-Regular.ttf $TARGET/usr/local/share/gui
cp system/etc/cnc-ctrl/StyleSheet.qss $TARGET/usr/local/share/gui

WORK_DIR=`pwd`

cd $TARGET
tar -cvf $WORK_DIR/$FNAME .
scp $WORK_DIR/$FNAME $DST

